export function printGRNDocument({ grnCode, date, supplierName, items = [], printedBy = '', generatedAt = '', isReprint = false, reprintedBy = '', reprintedAt = '' }) {
  const grnDate = date
    ? new Date(date).toLocaleDateString('en-PK', { year: 'numeric', month: 'long', day: 'numeric' })
    : '';

  let grandTotal = 0;
  const rows = items.map((item, idx) => {
    const amount = Number(item.amountReceived) || 0;
    grandTotal += amount;
    const mfr = item.manufacturer ? item.manufacturer.trim() : '';
    const mdl = item.model ? item.model.trim() : '';
    const extras = [mfr ? `Mfr: ${mfr}` : '', mdl ? `Model: ${mdl}` : ''].filter(Boolean).join(' | ');
    const extrasHtml = extras ? `<div class="item-meta">${extras}</div>` : '';
    return `<tr>
      <td>${idx + 1}</td>
      <td class="desc">${item.itemName || '-'}${extrasHtml}</td>
      <td>${item.orderedQty ?? '-'}</td>
      <td>${item.receivedQty ?? '-'}</td>
      <td>${item.rateEst != null ? Number(item.rateEst).toFixed(2) : '-'}</td>
      <td>${item.rateReceived != null ? Number(item.rateReceived).toFixed(2) : '-'}</td>
      <td>${amount > 0 ? amount.toFixed(2) : '-'}</td>
    </tr>`;
  }).join('');

  const footerParts = [];
  if (printedBy)   footerParts.push(`Generated by: <strong>${printedBy}</strong>`);
  if (generatedAt) {
    const label = isReprint ? 'Document Date:' : 'Date &amp; Time:';
    footerParts.push(`${label} ${generatedAt}`);
  }
  const reprintLine = isReprint
    ? `<span style="color:#b00;font-weight:600;">REPRINT</span> by: <strong>${reprintedBy || '-'}</strong>&nbsp;&nbsp;|&nbsp;&nbsp;Reprinted on: ${reprintedAt || '-'}`
    : '';

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Goods Receiving Note</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">
  <style>
    @page { size: A5; margin: 12mm 10mm 10mm 10mm; }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Poppins', sans-serif; font-size: 8.5pt; color: #111; background: #fff; }
    .watermark { position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%) rotate(-45deg); font-size: 70pt; font-weight: 900; color: rgba(160,0,0,0.07); letter-spacing: 5px; white-space: nowrap; pointer-events: none; user-select: none; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 6px; }
    .title { font-size: 17pt; font-weight: 700; letter-spacing: 0.3px; }
    .grn-meta { text-align: right; font-size: 8pt; line-height: 1.7; }
    .divider { border: none; border-top: 2px solid #aaa; margin-bottom: 7px; }
    .supplier-section { border: 1px solid #bbb; margin-bottom: 12px; }
    .supplier-row { display: flex; }
    .supplier-label { background: #e8e8e8; padding: 5px 10px; font-weight: 600; font-size: 8pt; white-space: nowrap; border-right: 1px solid #bbb; }
    .supplier-value { padding: 5px 10px; font-size: 8pt; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 8px; }
    thead tr { background: #e8e8e8; }
    th { padding: 5px 3px; font-weight: 600; text-align: center; border: 1px solid #bbb; font-size: 7.5pt; line-height: 1.4; }
    tbody tr td { border: 1px solid #ddd; padding: 4px 3px; text-align: center; font-size: 7.5pt; }
    tbody tr td.desc { text-align: left; padding-left: 5px; }
    tbody tr:nth-child(even) { background: #f9f9f9; }
    .item-meta { font-size: 6.5pt; color: #555; margin-top: 2px; font-style: italic; }
    .total-section { display: flex; justify-content: flex-end; margin-bottom: 24px; }
    .total-box { display: flex; border: 1px solid #bbb; }
    .total-label { background: #e8e8e8; padding: 5px 16px; font-weight: 600; font-size: 8.5pt; border-right: 1px solid #bbb; }
    .total-value { padding: 5px 16px; min-width: 80px; text-align: right; font-size: 8.5pt; }
    .signatures { display: flex; justify-content: space-between; margin-top: 60px; }
    .sig { font-weight: 700; font-size: 9pt; }
    .sig-line { border-top: 1px solid #555; width: 80px; margin-bottom: 5px; }
    .generated-footer { margin-top: 18px; font-size: 7pt; color: #888; border-top: 1px solid #ddd; padding-top: 5px; }
  </style>
</head>
<body>
  ${isReprint ? '<div class="watermark">DUPLICATE</div>' : ''}
  <div class="header">
    <div class="title">GOODS RECEIVING NOTE (GRN)</div>
    <div class="grn-meta">
      <div>GRN Number: ${grnCode}</div>
      <div>Date: ${grnDate}</div>
    </div>
  </div>
  <hr class="divider">
  <div class="supplier-section">
    <div class="supplier-row">
      <div class="supplier-label">Supplier Name</div>
      <div class="supplier-value">${supplierName}</div>
    </div>
  </div>
  <table>
    <thead>
      <tr>
        <th>S.No</th>
        <th>Item Name</th>
        <th>Qty<br>Ordered</th>
        <th>Qty<br>Received</th>
        <th>Rate<br>Est</th>
        <th>Rate<br>Received</th>
        <th>Amount<br>Received</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>
  <div class="total-section">
    <div class="total-box">
      <div class="total-label">Total</div>
      <div class="total-value">${grandTotal > 0 ? grandTotal.toFixed(2) : '-'}</div>
    </div>
  </div>
  <div class="signatures">
    <div class="sig"><div class="sig-line"></div>Store Keeper</div>
    <div class="sig"><div class="sig-line"></div>C.E.O.</div>
  </div>
  ${(footerParts.length > 0 || reprintLine) ? `<div class="generated-footer">${footerParts.join('&nbsp;&nbsp;|&nbsp;&nbsp;')}${footerParts.length > 0 && reprintLine ? '<br>' : ''}${reprintLine}</div>` : ''}
  <script>document.fonts.ready.then(() => window.print());</script>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const win = window.open(url, '_blank');
  if (win) setTimeout(() => URL.revokeObjectURL(url), 60000);
}
