export function printPODocument(result, { printedBy = '', generatedAt = '' } = {}) {
  const poItems = result?.records ? result.records : Array.isArray(result) ? result : [result];
  if (!poItems.length) return;

  const first = poItems[0];
  const poCode = result?.batchCode || first.code || '';
  const supplierName = first.supplier?.name || '';
  const poDate = first.poDate
    ? new Date(first.poDate).toLocaleDateString('en-PK', { year: 'numeric', month: 'long', day: 'numeric' })
    : '';

  let totalEst = 0;
  const rows = poItems.map((po, idx) => {
    const qty = Number(po.requiredQuantity) || 0;
    const rate = Number(po.orderedRate) || 0;
    const total = qty * rate;
    totalEst += total;
    return `<tr>
      <td>${idx + 1}</td>
      <td class="desc">${po.item?.name || '-'}</td>
      <td>${qty || '-'}</td>
      <td>${rate ? rate.toFixed(2) : '-'}</td>
      <td>${total > 0 ? total.toFixed(2) : '-'}</td>
      <td>${po.lastPurchaseQuantity ?? '-'}</td>
      <td>${po.lastPurchaseRate != null ? Number(po.lastPurchaseRate).toFixed(2) : '-'}</td>
    </tr>`;
  }).join('');

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Purchase Order</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">
  <style>
    @page { size: A5; margin: 12mm 10mm 10mm 10mm; }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Poppins', sans-serif; font-size: 8.5pt; color: #111; background: #fff; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 6px; }
    .title { font-size: 17pt; font-weight: 700; letter-spacing: 0.3px; }
    .po-meta { text-align: right; font-size: 8pt; line-height: 1.7; }
    .divider { border: none; border-top: 2px solid #aaa; margin-bottom: 7px; }
    .supplier-section { border: 1px solid #bbb; margin-bottom: 12px; }
    .supplier-row { display: flex; }
    .supplier-label { background: #e8e8e8; padding: 5px 10px; font-weight: 600; font-size: 8pt; white-space: nowrap; border-right: 1px solid #bbb; }
    .supplier-value { padding: 5px 10px; font-size: 8pt; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 8px; }
    thead tr { background: #e8e8e8; }
    th { padding: 5px 3px; font-weight: 600; text-align: center; border: 1px solid #bbb; font-size: 7.5pt; line-height: 1.4; }
    tbody tr td { border: 1px solid #ddd; padding: 4px 3px; text-align: center; font-size: 7.5pt; }
    tbody tr td.desc { text-align: left; padding-left: 5px; }
    tbody tr:nth-child(even) { background: #f9f9f9; }
    .total-section { display: flex; justify-content: flex-end; margin-bottom: 24px; }
    .total-box { display: flex; border: 1px solid #bbb; }
    .total-label { background: #e8e8e8; padding: 5px 16px; font-weight: 600; font-size: 8.5pt; border-right: 1px solid #bbb; }
    .total-value { padding: 5px 16px; min-width: 80px; text-align: right; font-size: 8.5pt; }
    .signatures { display: flex; justify-content: space-between; margin-top: 60px; padding-top: 4px; }
    .sig { font-weight: 700; font-size: 9pt; }
    .sig-line { border-top: 1px solid #555; width: 80px; margin-bottom: 5px; }
    .generated-footer { margin-top: 18px; font-size: 7pt; color: #888; border-top: 1px solid #ddd; padding-top: 5px; }
  </style>
</head>
<body>
  <div class="header">
    <div class="title">PURCHASE ORDER (PO)</div>
    <div class="po-meta">
      <div>PO Number: ${poCode}</div>
      <div>Date: ${poDate}</div>
    </div>
  </div>
  <hr class="divider">
  <div class="supplier-section">
    <div class="supplier-row">
      <div class="supplier-label">Supplier Name</div>
      <div class="supplier-value">${supplierName}</div>
    </div>
  </div>
  <table>
    <thead>
      <tr>
        <th>Item #</th>
        <th>Description</th>
        <th>Quantity<br>Req</th>
        <th>Unit Price<br>Est</th>
        <th>Total<br>Est</th>
        <th>Last Purchase<br>Qty</th>
        <th>Last Purchase<br>Rate</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>
  <div class="total-section">
    <div class="total-box">
      <div class="total-label">Total</div>
      <div class="total-value">${totalEst > 0 ? totalEst.toFixed(2) : '-'}</div>
    </div>
  </div>
  <div class="signatures">
    <div class="sig"><div class="sig-line"></div>Store Keeper</div>
    <div class="sig"><div class="sig-line"></div>C.E.O.</div>
  </div>
  ${(printedBy || generatedAt) ? `<div class="generated-footer">${printedBy ? `Generated by: <strong>${printedBy}</strong>` : ''}${printedBy && generatedAt ? '&nbsp;&nbsp;|&nbsp;&nbsp;' : ''}${generatedAt ? `Date &amp; Time: ${generatedAt}` : ''}</div>` : ''}
  <script>document.fonts.ready.then(() => window.print());</script>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const win = window.open(url, '_blank');
  if (win) setTimeout(() => URL.revokeObjectURL(url), 60000);
}

export function printGDDocument(row, { printedBy = '', generatedAt = '' } = {}) {
  if (!row) return;

  const gdCode      = row.code || '-';
  const department  = row.department?.name || '-';
  const requestDate = row.requestDate
    ? new Date(row.requestDate).toLocaleDateString('en-PK', { year: 'numeric', month: 'long', day: 'numeric' })
    : '-';
  const admissionNumber = row.admissionNumber || null;
  const comment         = row.comment || null;

  const tableRows = (row.gdItems || []).map((gi, idx) => {
    const itemName = gi.item?.name || '-';
    const qty      = gi.quantityRequested ?? '-';
    const status   = gi.status ?? 'open';
    return `<tr>
      <td>${idx + 1}</td>
      <td class="desc">${itemName}</td>
      <td>${qty}</td>
      <td><span class="status-badge status-${String(status).toLowerCase()}">${status}</span></td>
    </tr>`;
  }).join('');

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Goods Demand Note</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">
  <style>
    @page { size: A5; margin: 12mm 10mm 10mm 10mm; }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Poppins', sans-serif; font-size: 8.5pt; color: #111; background: #fff; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 6px; }
    .title { font-size: 17pt; font-weight: 700; letter-spacing: 0.3px; }
    .gd-meta { text-align: right; font-size: 8pt; line-height: 1.7; }
    .divider { border: none; border-top: 2px solid #aaa; margin-bottom: 7px; }
    .info-section { border: 1px solid #bbb; margin-bottom: 12px; }
    .info-row { display: flex; border-bottom: 1px solid #e0e0e0; }
    .info-row:last-child { border-bottom: none; }
    .info-label { background: #e8e8e8; padding: 5px 10px; font-weight: 600; font-size: 8pt; white-space: nowrap; border-right: 1px solid #bbb; min-width: 110px; }
    .info-value { padding: 5px 10px; font-size: 8pt; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 8px; }
    thead tr { background: #e8e8e8; }
    th { padding: 5px 3px; font-weight: 600; text-align: center; border: 1px solid #bbb; font-size: 7.5pt; line-height: 1.4; }
    tbody tr td { border: 1px solid #ddd; padding: 4px 3px; text-align: center; font-size: 7.5pt; }
    tbody tr td.desc { text-align: left; padding-left: 5px; }
    tbody tr:nth-child(even) { background: #f9f9f9; }
    .status-badge { padding: 1px 6px; border-radius: 10px; font-size: 7pt; font-weight: 600; }
    .status-open    { background: #dbeafe; color: #1d4ed8; }
    .status-partial { background: #fef9c3; color: #854d0e; }
    .status-closed  { background: #dcfce7; color: #166534; }
    .signatures { display: flex; justify-content: space-between; margin-top: 60px; padding-top: 4px; }
    .sig { font-weight: 700; font-size: 9pt; }
    .sig-line { border-top: 1px solid #555; width: 80px; margin-bottom: 5px; }
    .generated-footer { margin-top: 18px; font-size: 7pt; color: #888; border-top: 1px solid #ddd; padding-top: 5px; }
  </style>
</head>
<body>
  <div class="header">
    <div class="title">GOODS DEMAND NOTE (GD)</div>
    <div class="gd-meta">
      <div>GD No: <strong>${gdCode}</strong></div>
      <div>Date: ${requestDate}</div>
    </div>
  </div>
  <hr class="divider">
  <div class="info-section">
    <div class="info-row">
      <div class="info-label">Department</div>
      <div class="info-value">${department}</div>
    </div>
    ${admissionNumber ? `<div class="info-row"><div class="info-label">Admission No.</div><div class="info-value">${admissionNumber}</div></div>` : ''}
    ${comment ? `<div class="info-row"><div class="info-label">Comment</div><div class="info-value">${comment}</div></div>` : ''}
  </div>
  <table>
    <thead>
      <tr>
        <th>S.No</th>
        <th>Item Name</th>
        <th>Qty<br>Requested</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>${tableRows || '<tr><td colspan="4" style="text-align:center;padding:8px;">No items</td></tr>'}</tbody>
  </table>
  <div class="signatures">
    <div class="sig"><div class="sig-line"></div>Requested By</div>
    <div class="sig"><div class="sig-line"></div>Department Head</div>
    <div class="sig"><div class="sig-line"></div>Store Keeper</div>
  </div>
  ${(printedBy || generatedAt) ? `<div class="generated-footer">${printedBy ? `Generated by: <strong>${printedBy}</strong>` : ''}${printedBy && generatedAt ? '&nbsp;&nbsp;|&nbsp;&nbsp;' : ''}${generatedAt ? `Date &amp; Time: ${generatedAt}` : ''}</div>` : ''}
  <script>document.fonts.ready.then(() => window.print());</script>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  const url  = URL.createObjectURL(blob);
  const win  = window.open(url, '_blank');
  if (win) setTimeout(() => URL.revokeObjectURL(url), 60000);
}

export function printGINDocument(row, { printedBy = '', generatedAt = '' } = {}) {
  if (!row) return;

  const ginCode   = row.code || '-';
  const gdRef     = row.gdHeader?.code || row.gd?.code || '-';
  const department = row.department?.name || row.gdHeader?.department?.name || '-';
  const issuedBy  = row.issuedBy ? `${row.issuedBy.firstName} ${row.issuedBy.lastName}` : '-';
  const issueDate  = row.issueDate
    ? new Date(row.issueDate).toLocaleDateString('en-PK', { year: 'numeric', month: 'long', day: 'numeric' })
    : '-';
  const reqDateFallback = row.gdHeader?.requestDate
    ? new Date(row.gdHeader.requestDate).toLocaleDateString('en-PK', { year: 'numeric', month: 'short', day: 'numeric' })
    : '-';

  const ginItems = Array.isArray(row.ginItems) && row.ginItems.length > 0 ? row.ginItems : [];

  const tableRows = ginItems.map((gi, idx) => {
    const itemName   = gi.item?.name || '-';
    const qtyDemand  = gi.gdItem?.quantityRequested ?? gi.quantityRequested ?? '-';
    const qtyIssued  = gi.issuedQuantity ?? '-';
    const status     = gi.gdItem?.status ?? gi.status ?? '-';
    const reqDate    = gi.gdItem?.requestDate
      ? new Date(gi.gdItem.requestDate).toLocaleDateString('en-PK', { year: 'numeric', month: 'short', day: 'numeric' })
      : reqDateFallback;
    return `<tr>
      <td>${idx + 1}</td>
      <td class="desc">${itemName}</td>
      <td>${qtyDemand}</td>
      <td>${qtyIssued}</td>
      <td><span class="status-badge status-${String(status).toLowerCase()}">${status}</span></td>
      <td>${reqDate}</td>
    </tr>`;
  }).join('');

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Goods Issuance Note</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">
  <style>
    @page { size: A5; margin: 12mm 10mm 10mm 10mm; }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Poppins', sans-serif; font-size: 8.5pt; color: #111; background: #fff; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 6px; }
    .title { font-size: 17pt; font-weight: 700; letter-spacing: 0.3px; }
    .gin-meta { text-align: right; font-size: 8pt; line-height: 1.7; }
    .divider { border: none; border-top: 2px solid #aaa; margin-bottom: 7px; }
    .info-section { border: 1px solid #bbb; margin-bottom: 12px; }
    .info-row { display: flex; border-bottom: 1px solid #e0e0e0; }
    .info-row:last-child { border-bottom: none; }
    .info-label { background: #e8e8e8; padding: 5px 10px; font-weight: 600; font-size: 8pt; white-space: nowrap; border-right: 1px solid #bbb; min-width: 90px; }
    .info-value { padding: 5px 10px; font-size: 8pt; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 8px; }
    thead tr { background: #e8e8e8; }
    th { padding: 5px 3px; font-weight: 600; text-align: center; border: 1px solid #bbb; font-size: 7.5pt; line-height: 1.4; }
    tbody tr td { border: 1px solid #ddd; padding: 4px 3px; text-align: center; font-size: 7.5pt; }
    tbody tr td.desc { text-align: left; padding-left: 5px; }
    tbody tr:nth-child(even) { background: #f9f9f9; }
    .status-badge { padding: 1px 6px; border-radius: 10px; font-size: 7pt; font-weight: 600; }
    .status-open    { background: #dbeafe; color: #1d4ed8; }
    .status-partial { background: #fef9c3; color: #854d0e; }
    .status-closed  { background: #dcfce7; color: #166534; }
    .signatures { display: flex; justify-content: space-between; margin-top: 60px; padding-top: 4px; }
    .sig { font-weight: 700; font-size: 9pt; }
    .sig-line { border-top: 1px solid #555; width: 80px; margin-bottom: 5px; }
    .generated-footer { margin-top: 18px; font-size: 7pt; color: #888; border-top: 1px solid #ddd; padding-top: 5px; }
  </style>
</head>
<body>
  <div class="header">
    <div class="title">GOODS ISSUANCE NOTE (GIN)</div>
    <div class="gin-meta">
      <div>GIN No: <strong>${ginCode}</strong></div>
      <div>Issue Date: ${issueDate}</div>
    </div>
  </div>
  <hr class="divider">
  <div class="info-section">
    <div class="info-row">
      <div class="info-label">Department</div>
      <div class="info-value">${department}</div>
    </div>
    <div class="info-row">
      <div class="info-label">GD Reference</div>
      <div class="info-value">${gdRef}</div>
    </div>
    <div class="info-row">
      <div class="info-label">Issued By</div>
      <div class="info-value">${issuedBy}</div>
    </div>
  </div>
  <table>
    <thead>
      <tr>
        <th>S.No</th>
        <th>Item Name</th>
        <th>Qty<br>Demanded</th>
        <th>Qty<br>Issued</th>
        <th>Status</th>
        <th>Request<br>Date</th>
      </tr>
    </thead>
    <tbody>${tableRows || '<tr><td colspan="6" style="text-align:center;padding:8px;">No items</td></tr>'}</tbody>
  </table>
  <div class="signatures">
    <div class="sig"><div class="sig-line"></div>Store Keeper</div>
    <div class="sig"><div class="sig-line"></div>Received By</div>
  </div>
  ${(printedBy || generatedAt) ? `<div class="generated-footer">${printedBy ? `Generated by: <strong>${printedBy}</strong>` : ''}${printedBy && generatedAt ? '&nbsp;&nbsp;|&nbsp;&nbsp;' : ''}${generatedAt ? `Date &amp; Time: ${generatedAt}` : ''}</div>` : ''}
  <script>document.fonts.ready.then(() => window.print());</script>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const win = window.open(url, '_blank');
  if (win) setTimeout(() => URL.revokeObjectURL(url), 60000);
}
export function printAllGINs(rows, { printedBy = '', generatedAt = '' } = {}) {
  if (!Array.isArray(rows) || rows.length === 0) return;

  const printDate = new Date().toLocaleDateString('en-PK', { year: 'numeric', month: 'long', day: 'numeric' });

  let sno = 0;
  const tableRows = rows.map((row) => {
    const ginCode    = row.code || '-';
    const gdRef      = row.gdHeader?.code || row.gd?.code || '-';
    const department = row.department?.name || row.gdHeader?.department?.name || '-';
    const issueDate  = row.issueDate
      ? new Date(row.issueDate).toLocaleDateString('en-PK', { year: 'numeric', month: 'short', day: 'numeric' })
      : '-';
    const reqDateFallback = row.gdHeader?.requestDate
      ? new Date(row.gdHeader.requestDate).toLocaleDateString('en-PK', { year: 'numeric', month: 'short', day: 'numeric' })
      : '-';

    const ginItems = Array.isArray(row.ginItems) && row.ginItems.length > 0 ? row.ginItems : [];

    if (ginItems.length === 0) {
      sno++;
      return `<tr>
        <td>${sno}</td>
        <td>${ginCode}</td>
        <td>${gdRef}</td>
        <td>${department}</td>
        <td class="desc">${row.item?.name || '-'}</td>
        <td>-</td>
        <td>${row.issuedQuantity ?? '-'}</td>
        <td>-</td>
        <td>${issueDate}</td>
      </tr>`;
    }

    return ginItems.map((gi) => {
      sno++;
      const qtyDemand = gi.gdItem?.quantityRequested ?? gi.quantityRequested ?? '-';
      const qtyIssued = gi.issuedQuantity ?? '-';
      const status    = gi.gdItem?.status ?? gi.status ?? '-';
      const reqDate   = gi.gdItem?.requestDate
        ? new Date(gi.gdItem.requestDate).toLocaleDateString('en-PK', { year: 'numeric', month: 'short', day: 'numeric' })
        : reqDateFallback;
      return `<tr>
        <td>${sno}</td>
        <td>${ginCode}</td>
        <td>${gdRef}</td>
        <td>${department}</td>
        <td class="desc">${gi.item?.name || '-'}</td>
        <td>${qtyDemand}</td>
        <td>${qtyIssued}</td>
        <td><span class="status-badge status-${String(status).toLowerCase()}">${status}</span></td>
        <td>${reqDate}</td>
      </tr>`;
    }).join('');
  }).join('');

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>GIN Report</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">
  <style>
    @page { size: A4 landscape; margin: 10mm 10mm 10mm 10mm; }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Poppins', sans-serif; font-size: 8pt; color: #111; background: #fff; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 6px; }
    .title { font-size: 15pt; font-weight: 700; letter-spacing: 0.3px; }
    .meta { text-align: right; font-size: 7.5pt; line-height: 1.7; color: #555; }
    .divider { border: none; border-top: 2px solid #aaa; margin-bottom: 8px; }
    table { width: 100%; border-collapse: collapse; }
    thead tr { background: #e8e8e8; }
    th { padding: 5px 4px; font-weight: 600; text-align: center; border: 1px solid #bbb; font-size: 7.5pt; line-height: 1.4; }
    tbody tr td { border: 1px solid #ddd; padding: 4px 3px; text-align: center; font-size: 7.5pt; }
    tbody tr td.desc { text-align: left; padding-left: 5px; }
    tbody tr:nth-child(even) { background: #f9f9f9; }
    .status-badge { padding: 1px 6px; border-radius: 10px; font-size: 6.5pt; font-weight: 600; }
    .status-open    { background: #dbeafe; color: #1d4ed8; }
    .status-partial { background: #fef9c3; color: #854d0e; }
    .status-closed  { background: #dcfce7; color: #166534; }
    .footer { margin-top: 20px; display: flex; justify-content: space-between; }
    .sig { font-weight: 700; font-size: 8.5pt; }
    .sig-line { border-top: 1px solid #555; width: 80px; margin-bottom: 4px; }
    .generated-footer { margin-top: 14px; font-size: 7pt; color: #888; border-top: 1px solid #ddd; padding-top: 5px; }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="title">GOODS ISSUANCE NOTE — ALL RECORDS</div>
      <div style="font-size:7.5pt;color:#555;margin-top:2px;">Total: ${rows.length} GIN(s)</div>
    </div>
    <div class="meta">
      <div>Print Date: ${printDate}</div>
    </div>
  </div>
  <hr class="divider">
  <table>
    <thead>
      <tr>
        <th>S.No</th>
        <th>GIN No</th>
        <th>GD Ref</th>
        <th>Department</th>
        <th>Item Name</th>
        <th>Qty<br>Demanded</th>
        <th>Qty<br>Issued</th>
        <th>Status</th>
        <th>Request<br>Date</th>
      </tr>
    </thead>
    <tbody>${tableRows}</tbody>
  </table>
  <div class="footer">
    <div class="sig"><div class="sig-line"></div>Store Keeper</div>
    <div class="sig"><div class="sig-line"></div>Department Head</div>
    <div class="sig"><div class="sig-line"></div>C.E.O.</div>
  </div>
  ${(printedBy || generatedAt) ? `<div class="generated-footer">${printedBy ? `Generated by: <strong>${printedBy}</strong>` : ''}${printedBy && generatedAt ? '&nbsp;&nbsp;|&nbsp;&nbsp;' : ''}${generatedAt ? `Date &amp; Time: ${generatedAt}` : ''}</div>` : ''}
  <script>document.fonts.ready.then(() => window.print());</script>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const win = window.open(url, '_blank');
  if (win) setTimeout(() => URL.revokeObjectURL(url), 60000);
}
